todoproject/todo_list/urls.py
from django.urls import path
from django.views.generic import TemplateView

from todo_list.views import index_view, ToDoListIndexView, ToDoListView, ToDoListDoneView, ToDoDetailView, \
    ToDoItemCreateView, ToDoItemUpdateView, ToDoItemDeleteView, task_status

app_name = "todo_list"

urlpatterns = [
    # path('', index_view, name="index"),
    # path('', ToDoListIndexView.as_view(), name="index"),
    path('', ToDoListIndexView.as_view(), name="index"),
    path('<int:pk>/', ToDoDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', ToDoItemUpdateView.as_view(), name="update"),
    path('<int:pk>/confirm-delete/', ToDoItemDeleteView.as_view(), name="delete"),

    path('list/', ToDoListView.as_view(), name="list"),
    path('done/', ToDoListDoneView.as_view(), name="done"),
    path('create/', ToDoItemCreateView.as_view(), name="create"),
    path('task-status/', task_status, name="task_status"),
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path('todos/', include('todo_list.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns.extend(debug_toolbar_urls())

todoproject/email_newsletters/models.py
from django.db import models

# Create your models here.

todoproject/todo_list/models.py
from django.db import models
from django.urls import reverse


# class ActiveToDoItemManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter(archived=False)
#
#     def done(self):
#         return self.get_queryset().filter(done=True)

class ToDoItemQuerySet(models.QuerySet):

    def active(self):
        return self.filter(archived=False)

    def done(self):
        return self.filter(done=True)

class ToDoItem(models.Model):
    class Meta:
        ordering = "id",
        verbose_name = "ToDo Item"


    title = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=False)
    done = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

    objects = ToDoItemQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse(
            "todo_list:detail",
            kwargs={"pk": self.pk},
        )

    def __str__(self):
        return self.title

todoproject/todo_list/forms.py
from django import forms

from todo_list.models import ToDoItem


class ToDoItemSearchForm(forms.Form):
    search = forms.CharField(
        label='search todo items',
        required=False,
    )

class ToDoItemCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ("title", "description")

        widgets = {
           "description": forms.Textarea(
               attrs={"cols": 30, "rows": 5},
           )
        }

        help_texts = {
            "description": "Some useful help text.",
        }

class ToDoItemUpdateForm(forms.ModelForm):
    class Meta(ToDoItemCreateForm.Meta):
        fields = ("title", "description", "done")

todoproject/email_newsletters/views.py
from django.shortcuts import render

# Create your views here.

todoproject/todo_list/views.py
from celery.result import AsyncResult
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery, TrigramSimilarity
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.db import models
from todo_list.forms import ToDoItemCreateForm, ToDoItemUpdateForm, ToDoItemSearchForm
from todo_list.models import ToDoItem
from todo_list.tasks import notify_admin_todo_archived


def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = ToDoItem.objects.all()
    context = {"todo_items": todo_items[:3]}
    return render(request, template_name="todo_list/index.html", context=context)


# class ToDoListIndexView(TemplateView):
#     template_name = "todo_list/index.html"
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["todo_items"] = ToDoItem.objects.all()
#         return context


class ToDoListView(ListView):

    TITLE_WEIGHT = 0.7
    DESCRIPTION_WEIGHT = 0.4

    # model = ToDoItem
    queryset = ToDoItem.objects.active()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update(form=ToDoItemSearchForm(self.request.GET))
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if search := self.request.GET.get("search"):
            # example 0
            # qs = qs.filter(
            #     models.Q(title__icontains=search)
            #     | models.Q(description__icontains=search)
            # )
            # example 1
            # qs = qs.annotate(
            #     search=SearchVector('title', 'description'),
            # ).filter(search=search)
            # example 2
            # search_vector = SearchVector('title', 'description')
            # search_query = SearchQuery(search)
            # qs = qs.annotate(
            #     search=search_vector,
            #     rank=SearchRank(search_vector, search_query),
            # ).filter(search=search_query).order_by("-rank", "pk")
            # example 3
            # qs = qs.annotate(
            #     similarity = TrigramSimilarity("title", search),
            # ).filter(similarity__gt=0.1).order_by("-similarity","pk")
            # example 4
            qs = qs.annotate(
                title_similarity = TrigramSimilarity("title", search),
                description_similarity = TrigramSimilarity("description", search),
                combined_similarity=(
                        (models.F("title_similarity") * self.TITLE_WEIGHT)
                        + (models.F("description_similarity") * self.DESCRIPTION_WEIGHT)
                ),
            ).filter(combined_similarity__gt=0.07).order_by(
                "-combined_similarity",
                "-title_similarity",
                "-description_similarity",
                "pk",
            )
        return qs


class ToDoListIndexView(ListView):
    template_name = "todo_list/index.html"
    queryset = ToDoItem.objects.active()[:3]


class ToDoListDoneView(ListView):

    queryset = ToDoItem.objects.active().done()
    extra_context = {
        "form": ToDoItemSearchForm(),
    }


class ToDoDetailView(DetailView):
    # model = ToDoItem
    queryset = ToDoItem.objects.active()


class ToDoItemCreateView(CreateView):
    model = ToDoItem
    form_class = ToDoItemCreateForm
    # fields = ("title", "description")


class ToDoItemUpdateView(UpdateView):
    model = ToDoItem
    template_name_suffix = "_update_form"
    form_class = ToDoItemUpdateForm
    # fields = ("title", "description", "done")


class ToDoItemDeleteView(DeleteView):
    # model = ToDoItem
    queryset = ToDoItem.objects.active()
    success_url = reverse_lazy("todo_list:list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        # notify_admin_todo_archived.delay(todo_id=self.object.pk)
        notify_admin_todo_archived.delay_on_commit(todo_id=self.object.pk)
        return HttpResponseRedirect(success_url)


def task_status(request: HttpRequest) -> HttpResponse:
    task_id = request.GET.get("task_id") or ""
    context = {"task_id": task_id}
    result = AsyncResult(task_id)
    context.update(status=result.status, ready=result.ready, result=result.result)
    return render(
        request,
        template_name="todo_list/task-status.html",
        context=context,
    )

todoproject/email_newsletters/templates/email_newsletters/welcome_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
Hello, <b>{{ name }}</b>!

<p>We're so <u>glad</u> to see you!</p>

<div>
    Thanks, <br>
    GoodBye.
</div>

<div>
    <p>My contacts: +7999999999</p>
    <img 
         src="https://lp-cms-production.imgix.net/features/2013/04/sunrise1_cs.jpg?auto=format,compress&q=72&w=1440&h=810&fit=crop" 
         alt="welcome-pic"
    >
</div>

</body>
</html>

todoproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock title %}
    </title>
</head>
<body>
{% include 'components/navbar.html' %}
{% block body %}
    Base body
{% endblock body %}

<footer>
    &copy; Django TODO App
    {% block footer %}

    {% endblock %}
</footer>

</body>
</html>

todoproject/templates/components/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'todo_list:index' %}">ToDo List</a></li>
        <li><a href="#">About</a></li>
    </ul>
</nav>

todoproject/templates/index.html
{% extends 'base.html' %}

{% block title %}
	TODO App Index
{% endblock %}

{% block body %}
    <h1>Welcome to our TODO App!</h1>
    <h2>Work in progress</h2>
    <h3>
        It is {% now "jS F Y H:i" %}
    </h3>
{% endblock %}

todoproject/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
	ToDo list
{% endblock %}

todoproject/todo_list/templates/todo_list/components/todo_items_list.html
<ul>
    {% for todo_item in object_list %}
        <li>
        <a href="{% url 'todo_list:detail' pk=todo_item.pk %}">
            {{ todo_item.title }}
            {% if todo_item.done %}
                ✔️
            {% else %}
                ❌
            {% endif %}
        </a>
        </li>
    {% endfor %}
</ul>

todoproject/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %}

{% block title %}
	ToDo list App
{% endblock %}

{% block body %}
	<h1>ToDo List App</h1>
    <ul>
        <li><a href="{% url 'todo_list:list' %}">All todo items</a></li>
        <li><a href="{% url 'todo_list:done' %}">Done todo items</a></li>
        <li><a href="{% url 'todo_list:create' %}">Create ToDo Item</a></li>
    </ul>

    <h2>ToDos:</h2>
    {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todoproject/todo_list/templates/todo_list/task-status.html
{% extends 'todo_list/base.html' %}

{% block title %}
	Task Status
{% endblock %}

{% block body %}
	<h2>Task {{ task_id }} status</h2>
    <div>
        <p>
            <b>Status:</b> {{ status }}
        </p>
        <p>
            <b>Ready:</b> {{ ready }}
        </p>
        <p>
            <b>Result:</b> {{ result }}
        </p>
    </div>
    <p>
        <form method="get">
            <label for="task-id">Task ID</label>
            <input id="task-id" name="task_id" type="text" value="{% firstof task_id '' %}">
            <input type="submit" value="Check status">
        </form>
    </p>
{% endblock %}

todoproject/todo_list/templates/todo_list/todoitem_confirm_delete.html
{% extends 'todo_list/base.html' %}

{% block title %}
	Confirm Delete ToDo Item #{{ object.id }}
{% endblock %}

{% block body %}
	<h2>Confirm delete "{{ object.title }}"</h2>
    <p>
        Are you sure you want to delete Todo Item <code>{{ object.title }}</code>
        with description <i>{{ object.description }}</i>?
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Delete</button>
    </form>
    <div>
        <a href="{% url 'todo_list:detail' object.pk %}">
            Back to ToDo Item details
        </a>
    </div>
{% endblock %}

todoproject/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'todo_list/base.html' %}

{% block title %}
	ToDo #{{ object.id }}
{% endblock %}

{% block body %}
    <h3>ToDo:</h3>
    <div>
        <div>Title: <strong>{{ object.title }}</strong></div>
        <div>Done: <strong>{{ object.done }}</strong></div>
        <div>Description: <strong>{{ object.description }}</strong></div>
    </div>

    <ul>
        <li>
            <a href="{% url 'todo_list:update' object.pk %}">
                Update ToDo Item
            </a>
        </li>
        <li>
            <a href="{% url 'todo_list:delete' object.pk %}">
                Delete ToDo Item
            </a>
        </li>
    </ul>
{% endblock %}

todoproject/todo_list/templates/todo_list/todoitem_form.html
{% extends 'todo_list/base.html' %}

{% block title %}
	Create new ToDo Item
{% endblock %}

{% block body %}
    <h3>Create new ToDo:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
{% endblock %}

todoproject/todo_list/templates/todo_list/todoitem_list.html
{% extends 'todo_list/base.html' %}

{% block title %}
	ToDo list
{% endblock %}

{% block body %}
    <h3>ToDos:</h3>
    <form>
        {{ form.as_div }}
        <button type="submit">Search</button>
    </form>
    {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todoproject/todo_list/templates/todo_list/todoitem_update_form.html
{% extends 'todo_list/base.html' %}

{% block title %}
	Update ToDo Item #{{ object.id }}
{% endblock %}

{% block body %}
    <h3>Update ToDo:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

    <div>
        <a href="{% url 'todo_list:detail' object.pk %}">
            Back to ToDo Item details
        </a>
    </div>

{% endblock %}